Features/ari.choc/crea vista y form coord
nicolasrojas88/squad3_services pull request #19
Opened 2023-06-03 00:26 UTC by blackmonk69

2023-06-03 13:30 UTC, maxwellnewage requested changes

2023-06-03 13:30 UTC, maxwellnewage commented on reservas/forms.py
> +class Formu_Empleado(forms.Form):
el nombre debería ser "FormEmpleado", clases en PascalCase.

2023-06-03 13:38 UTC, blackmonk69 commented on reservas/forms.py
> +class Formu_Empleado(forms.Form):
hola maxi. listo los cambios

2023-06-03 14:01 UTC, maxwellnewage requested changes

2023-06-03 14:01 UTC, maxwellnewage commented on reservas/forms.py
> +class FormuEmpleado(forms.Form):
sigue diciendo "Formu", es "Form" o "Formulario"

2023-06-03 16:19 UTC, blackmonk69 commented on reservas/forms.py
> +class FormuEmpleado(forms.Form):
listo pasa a ser FormEmpleado

2023-06-03 16:46 UTC, maxwellnewage approved these changes

2023-06-05 20:11 UTC, nicolasrojas88 approved these changes

2023-06-05 20:12 UTC, nicolasrojas88 commented
Conflictos resueltos!!

2023-06-05 20:12 UTC, merged